# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robby Valentine
email: info@pimderks.com
description: > #
  The official website for multi-instrumentalist, songwriter and producer
  Robby Valentine from the Netherlands.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robbyvalentine.nl" # the base hostname & protocol for your site
future: true

# Where things are
source: ./src/jekyll
destination: ./www
keep_files: [static]

# Build settings
markdown: kramdown

permalink: /news/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "albums"
    values:
      layout: release
  - scope:
      path: ""
      type: "compilations"
    values:
      layout: release
  - scope:
      path: ""
      type: "singles"
    values:
      layout: release
  - scope:
      path: ""
      type: "collaborations"
    values:
      layout: release
  - scope:
      path: ""
      type: "songs"
    values:
      layout: song
  - scope:
      path: ""
      type: "live"
    values:
      layout: live
  - scope:
      path: ""
      type: "shop"
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# Collections
collections:
  albums:
    output: "true"
    permalink: /music/albums/:title/
  compilations:
      output: "true"
      permalink: /music/compilations/:title/
  singles:
    output: "true"
    permalink: /music/singles/:title/
  collaborations:
    output: "true"
    permalink: /music/collaborations/:title/
  guest:
    output: "false"
  songs:
    output: "true"
    permalink: /music/songs/:title/
  live:
    output: "true"
    permalink: /live/:year-:month-:day/
  timeline:
    output: "false"
  shop:
    output: "false"
  faq:
    output: "false"